# Generated by Django 6.0 on 2026-01-15 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_letter_subscription', to='publishing.newsletter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
