# Generated by Django 6.0 on 2026-01-15 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0002_subscriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesEditors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_article', to='publishing.articles')),
                ('news_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_news_letter', to='publishing.newsletter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_editor', to='publishing.articles')),
            ],
        ),
    ]
