# Generated by Django 6.0 on 2026-01-15 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0003_articleseditors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleseditors',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
