# Generated by Django 6.0 on 2026-01-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0004_alter_articleseditors_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='journalist',
            field=models.BooleanField(default=False),
        ),
    ]
