# Generated by Django 6.0 on 2026-01-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0005_users_journalist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
            ],
        ),
    ]
