# Generated by Django 6.0 on 2026-01-20 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0006_testtemp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTemp',
        ),
    ]
