# Generated by Django 6.0 on 2026-01-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0007_delete_testtemp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='users',
            name='journalist',
        ),
        migrations.RemoveField(
            model_name='users',
            name='publisher',
        ),
        migrations.AddField(
            model_name='users',
            name='popcorn',
            field=models.BooleanField(default=True),
        ),
    ]
