# Generated by Django 6.0 on 2026-02-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0008_remove_users_editor_remove_users_journalist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='popcorn',
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(default='user-role', max_length=50),
            preserve_default=False,
        ),
    ]
